# An explanation of this configuration file and what the options do can be found at https://raycastedantiesp.cubi.games/config/
config-version: '2.0'
checks:
    player:
        enabled: true
        hide-sounds-when-hidden: true
        max-occluding-count: 3
        always-show-radius: 8
        raycast-radius: 128
        hide-on-spawn-distance: 24
        visible-recheck-interval-ticks: 5  # -1 disables visible rechecks. When set to -1, once an entity is shown by any mechanism, it will be permanently visible.
        keep-client-entity-when-hidden: false
        only-check-sneaking: false
    entity:
        enabled: true
        hide-sounds-when-hidden: true
        max-occluding-count: 3
        always-show-radius: 8
        raycast-radius: 92
        hide-on-spawn-distance: 24
        visible-recheck-interval-ticks: 5 # -1 disables visible rechecks. When set to -1, once an entity is shown by any mechanism, it will be permanently visible.
        keep-client-entity-when-hidden: false
        excluded-types:
            # Projectiles move very quickly, giving limited time for the raycast engine to process them. This could cause the player not to have enough time to dodge the projectile, so they are always visible by default.
            - minecraft:arrow
            - minecraft:spectral_arrow
            - minecraft:fireball
            - minecraft:dragon_fireball
            - minecraft:small_fireball
            - minecraft:firework_rocket
            - minecraft:wither_skull
            - minecraft:breeze_wind_charge
            - minecraft:wind_charge
            - minecraft:ender_pearl
            - minecraft:evoker_fangs
            - minecraft:shulker_bullet

            # Potions and area effect clouds can damage players even if not visible. A reasonable always-show-radius mitigates these issues, so exempting these entities is not necessary.
            # If your server relies on potion pvp where knowing the exact number of potions someone else has used is an unfair advantage, you may want to un-exempt these entities.
            - minecraft:area_effect_cloud
            - minecraft:lingering_potion
            - minecraft:splash_potion
            - minecraft:potion # Note: the "potion" entity was removed in 1.21.5 and replaced with "splash_potion" and "lingering_potion". If you are on 1.21.4, you can comment out the above two entry. If you are on 1.21.5+ you should instead comment out this entry.

            # Lightning is short-lived and expected to be visible to people who cannot see the block being struck.
            - minecraft:lightning_bolt

            - minecraft:ender_dragon
            - minecraft:wither
            - minecraft:warden

            # These entities are not seen in normal gameplay, and are usually part of custom mechanics.
            # If you un-exempt these entities, it is likely that other plugins (such as hologram or NPC plugins) will break.
            - minecraft:block_display
            - minecraft:text_display
            - minecraft:item_display
            - minecraft:interaction
            - minecraft:mannequin
            # Falling blocks are often used in custom mechanics, especially by plugins made before display entities were added to the game.
            # Therefore, exempting them can make sense. However, falling blocks also occur in regular gameplay,
            # and can provide insight about players which are not visible.
            # Therefore, falling blocks are not exempted by default.
            #- minecraft:falling_block

            # You can add more excluded types using the name for the entity which would be used by the /summon <entity> command, adding "- <entity>" to the list above.
    tile-entity:
        enabled: true
        max-occluding-count: 3
        always-show-radius: 8
        raycast-radius: 64
        hide-on-spawn-distance: 24
        visible-recheck-interval-ticks: -1  # -1 disables visible rechecks. When set to -1, once an entity is shown by any mechanism, it will be permanently visible.
    sound-effects:
        enabled: true
        max-occluding-count: 3
        always-play-radius: 8
        raycast-radius: 48
    chunk-section:
        enabled: false
        max-occluding-count: 6
        always-show-radius-chunks: 2
        visible-recheck-interval-ticks: -1
engine:
    mode: async
    async:
        processing-threads: 1 # 1 thread is sufficient for hundreds of players, I do not recommend increasing this value blindly.
    netty:
block-processor:
    mode: packetevents
    track-all-blocks: false
    packetevents:
        tile-entity-exempted-ids:
            #- 9779 - Beacon ID on 1.21.11. To see what the beacon ID is for your server version, run the command "/antiesp print-block-ids". This will dump a massive list of all the block ID to block name mappings in the console. Search your logs for "beacon" (or whatever other tile entity you'd like to exempt) and add the associated ID here
        tile-entity-force-included-ids:
debug:
    info-level: 5
    info-exempted-classes:
    warn-level: 5
    warn-exempted-classes:
    error-level: 5
    error-exempted-classes:
    particles: false
    timings: false
updates:
    check-release: true
    check-beta: true
    check-alpha: true
    notify-in-game: true # When false, update checks only notify the console. When true, players with the correct permission are notified.
